### ISSUE TITLE
Error: invalid operands (*UND* and *ABS* sections) for `<<'

### ISSUE THREAD

**Issue by mariobaldini** [akatrevorjay/edid-generator#19]
Hi, 

I am trying to use the tool in Fedora 33, kernel 5.8.11, gcc version 10.2.1 and stuck in the following error: 

```
./modeline2edid - <<< 'Modeline "2560x1080_60.00"  230.00  2560 2720 2992 3424  1080 1083 1093 1120 -hsync +vsync ratio=21:9'
...
Wrote 2560x1080_60.00.S

$ make:

cc -c -DCRC="0x00" -o 2560x1080_60.00.o 2560x1080_60.00.S
edid.S: Assembler messages:
edid.S:171: Warning: value 0x121 truncated to 0x21
edid.S:270: Warning: repeat < 0; .fill ignored
edid.S:175: Error: invalid operands (*UND* and *ABS* sections) for `<<'
make: *** [Makefile:16: 2560x1080_60.00.o] Error 1
$
```

Any suggestion on what could be the problem?

Is the generated .bin file generic and related only to the resolution/rate? (independently from GPU, SO, etc..)

If so, could the 2560x1080@60 be also committed to the repo, please? It is a common resolution for newer ultrawide displays and really helpful for users to direct download and attempt the fix. 

Thank you

[2560x1080_60.00.S.txt](https://github.com/akatrevorjay/edid-generator/files/5289727/2560x1080_60.00.S.txt)

**Comment by mariobaldini** [comment]
Confirmed on Ubuntu 20.04.1:

``` 
ubuntu@ubuntu:~/edid-generator$ ./modeline2edid 
Searching for modelines in '/dev/stdin'
Modeline "2560x1080_60.00" 230.00 2560 2720 2992 3424 1080 1083 1093 1120 -hsync +vsync ratio=21:9
-- Found modeline: Modeline "2560x1080_60.00" 230.00 2560 2720 2992 3424 1080 1083 1093 1120 -hsync +vsync ratio=21:9
Wrote 2560x1080_60.00.S
^C
ubuntu@ubuntu:~/edid-generator$ make
cc -c -DCRC="0x00" -o 2560x1080_60.00.o 2560x1080_60.00.S
edid.S: Assembler messages:
edid.S:171: Warning: value 0x121 truncated to 0x21
edid.S:270: Warning: repeat < 0; .fill ignored
edid.S:175: Error: invalid operands (*UND* and *ABS* sections) for `<<'
make: *** [Makefile:16: 2560x1080_60.00.o] Error 1
ubuntu@ubuntu:~/edid-generator$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-10ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2) 
ubuntu@ubuntu:~/edid-generator$
```

**Comment by MiltosKoutsokeras** [comment]
Hello,

I have the same error when sing this modeline:

`Modeline "1920x240_120.00" 74.75 1920 1976 2160 2400 240 243 253 261 -hsync +vsync ratio=8:1`

I'm trying to create a proper 240 line progressive EDID for KMS video and emulation. 240p is the way to go for most arcade and console games of the 1980s, early 1990s.

I think the error is in line 175 but is caused by the fixed list of aspect ratios in the `edid.S` file

```
29 
30 /* EDID 1.3 standard definitions */
31 #define XY_RATIO_16_10  0b00
32 #define XY_RATIO_4_3    0b01
33 #define XY_RATIO_5_4    0b10
34 #define XY_RATIO_16_9   0b11
35
```

In line 175 it seems there is a calculation involving `XY_RATIO_<aspect ratio>`  which is not properly set because the tool creates this:

```
/* 1920x240_120.00: Modeline "1920x240_120.00" 74.75 1920 1976 2160 2400 240 243 253 261 -hsync +vsync ratio=8:1 */
#define HSYNC_POL 1
#define VSYNC_POL 1
#define YPULSE (63+10)
#define XPULSE 184
#define YPIX 240
#define XPIX 1920
#define VFREQ 60
#define DPI 96
#define CLOCK 74750
#define VERSION 1
#define REVISION 3
#define XOFFSET 56
#define YOFFSET (63+3)
#define XY_RATIO XY_RATIO_8_1
#define YBLANK 21
#define XBLANK 480
#define TIMING_NAME "1920x240_120.00"
#include "edid.S"
```

which has the unknown `XY_RATIO_8_1`. I tried to change the edid.S file as follows:

```
diff --git a/edid.S b/edid.S
index ef082dc..2d78282 100644
--- a/edid.S
+++ b/edid.S
@@ -32,6 +32,7 @@
 #define XY_RATIO_4_3   0b01
 #define XY_RATIO_5_4   0b10
 #define XY_RATIO_16_9  0b11
+#define XY_RATIO_8_1   0b01
 
 /* Provide defaults for the timing bits */
 #ifndef ESTABLISHED_TIMING1_BITS
```

because I need the EDID to override for 4:3 VGA CRT Display. I compiled and saved the output to `/lib/firmware/edid/1920x240.bin` and also created `/etc/modprobe.d/drm-kms-helper.conf` with contents:

```
options drm_kms_helper edid_firmware=edid/1920x240.bin
```

Rebooted and no change to resolution. Firmware cannot be loaded due to CRC probably. Debian 10 x86_64 on Intel NUC 8 i3.

**Comment by yvvas** [comment]
I am also seeing this problem with a DQHD 5120x1440p monitor.

```
Error: invalid operands (*UND* and *ABS* sections) for `<<'
```

**Comment by mariobaldini** [comment]
FYI: ultimately the solution for my issue (21:9 screen ratio) was fixed changing the BIOS mode to UEFI, and not really applying any of the edid changes (a plethora of distinct attempts). Info reported by the monitor was ok, but somehow when BIOS features were enabled some component got lost (in firmware, driver, .. don't know).

Also, "UEFI with BIOS compatible boot" option also didn't work; only when I selected "UEFI only"

**Comment by lodriguez** [comment]
Not sure why this issue get closed. Even if op solved a different problem, the problem with edid-generator still persists. I'm still running in this issue

**Comment by onyxiarivera** [comment]
Experiencing this issue as well when trying to make a 3:2 modeline for my Surface Pro 7.

```
nyx@charred ~/edid-generator (master)> ./modeline2edid
Searching for modelines in '/dev/stdin'
Modeline "surface7pro"  426.00  2736 2952 3248 3760  1824 1827 1837 1890 -hsync +vsync ratio=3:2
-- Found modeline: Modeline "surface7pro" 426.00 2736 2952 3248 3760 1824 1827 1837 1890 -hsync +vsync ratio=3:2
Wrote surface7pro.S
^C⏎                                                                                                                 nyx@charred ~/edid-generator (master) [SIGINT]> ls
1024x768.bin   1280x720.bin   1680x1050.bin  2560x1440.bin  3840x2160.bin  edid.S             Makefile
1024x768.S     1280x720.S     1680x1050.S    2560x1440.S    3840x2160.S    EXAMPLE_MODELINES  modeline2edid*
1280x1024.bin  1600x1200.bin  1920x1080.bin  2880x1800.bin  800x600.bin    hex                README.md
1280x1024.S    1600x1200.S    1920x1080.S    2880x1800.S    800x600.S      LICENSE            surface7pro.S
nyx@charred ~/edid-generator (master)> make
cc -c -DCRC="0x00" -o surface7pro.o surface7pro.S
edid.S: Assembler messages:
edid.S:171: Warning: value 0x137 truncated to 0x37
edid.S:175: Error: invalid operands (*UND* and *ABS* sections) for `<<'
make: *** [Makefile:16: surface7pro.o] Error 1
nyx@charred ~/edid-generator (master) [2]> 
```
